In [6]:
import numpy as np
import random

In [7]:
#1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
#2
m = np.zeros((3, 3), dtype=int)

In [54]:
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
#3
m2 = np.random.randint(1, 11, size=(5, 5))

In [18]:
m2

array([[ 5,  8,  6,  7, 10],
       [ 7,  5,  3,  6,  1],
       [ 9, 10,  4,  4,  2],
       [10,  8,  3,  7,  6],
       [10, 10,  1, 10,  4]])

In [15]:
#4
m3 = np.random.random(size=(4, 4))

In [16]:
m3

array([[0.44586657, 0.19433362, 0.57133055, 0.8748134 ],
       [0.36775899, 0.7646266 , 0.38689792, 0.18016791],
       [0.60775575, 0.38379019, 0.14271326, 0.84162654],
       [0.67862463, 0.53669997, 0.53522145, 0.06994787]])

In [25]:
#5
b = np.random.randint(1, 11, size=5)
c = np.random.randint(1, 11, size=5)

In [26]:
b

array([3, 4, 8, 8, 9])

In [27]:
c

array([8, 3, 2, 3, 5])

In [28]:
sum = b + c
diff = b - c
mult = b * c

In [29]:
sum

array([11,  7, 10, 11, 14])

In [30]:
diff

array([-5,  1,  6,  5,  4])

In [31]:
mult

array([24, 12, 16, 24, 45])

In [32]:
#6
d = np.random.randint(1, 11, size=7)
e = np.random.randint(1, 11, size=7)

In [43]:
d

array([7, 6, 1, 8, 3, 3, 4])

In [44]:
e

array([5, 3, 5, 9, 2, 2, 5])

In [33]:
np.dot(d, e)

162

In [34]:
#7
m4 = np.random.randint(1, 11, size=(2, 2))
m5 = np.random.randint(1, 11, size=(2, 3))

In [39]:
m4

array([[9, 3],
       [6, 8]])

In [40]:
m5

array([[3, 7, 1],
       [4, 5, 5]])

In [41]:
np.dot(m4, m5)

array([[39, 78, 24],
       [50, 82, 46]])

In [42]:
#8
m6 = np.random.randint(1, 11, size=(3, 3))

In [45]:
m6

array([[4, 7, 5],
       [1, 1, 4],
       [7, 9, 7]])

In [47]:
m6_inv = np.linalg.inv(m6)

In [48]:
m6_inv

array([[-0.70731707, -0.09756098,  0.56097561],
       [ 0.51219512, -0.17073171, -0.26829268],
       [ 0.04878049,  0.31707317, -0.07317073]])

In [49]:
#9
m7 = np.random.random(size=(4, 4))

In [50]:
m7

array([[0.90252672, 0.83501008, 0.77727996, 0.17615153],
       [0.78510121, 0.55861671, 0.62520018, 0.65954005],
       [0.1385951 , 0.78380145, 0.69872475, 0.27647863],
       [0.50032113, 0.69818557, 0.44182978, 0.24054412]])

In [51]:
m7_T=m7.T

In [52]:
m7_T

array([[0.90252672, 0.78510121, 0.1385951 , 0.50032113],
       [0.83501008, 0.55861671, 0.78380145, 0.69818557],
       [0.77727996, 0.62520018, 0.69872475, 0.44182978],
       [0.17615153, 0.65954005, 0.27647863, 0.24054412]])

In [66]:
#10
m8 = np.random.randint(1, 11, size=(3, 4))
f = np.random.randint(1, 11, size=4)

In [67]:
m8

array([[7, 4, 1, 6],
       [9, 6, 1, 3],
       [4, 7, 6, 6]])

In [68]:
f

array([10,  6,  1,  6])

In [69]:
np.dot(m8, f)

array([131, 145, 124])

In [70]:
#11
m9 = np.random.random(size=(2, 3))
g = np.random.random(size=3)

In [73]:
m9

array([[0.44112463, 0.81513611, 0.46742648],
       [0.35950079, 0.79221699, 0.70582094]])

In [72]:
g

array([0.98073537, 0.30307932, 0.07272651])

In [74]:
np.dot(m9, g)

array([0.71367172, 0.64401162])

In [75]:
#12
m10 = np.random.randint(1, 11, size=(2, 2))
m11 = np.random.randint(1, 11, size=(2, 2))

In [76]:
m10

array([[6, 3],
       [9, 8]])

In [77]:
m11

array([[4, 3],
       [6, 8]])

In [78]:
np.multiply(m10, m11)

array([[24,  9],
       [54, 64]])

In [79]:
#13
m12 = np.random.randint(1, 11, size=(2, 2))
m13 = np.random.randint(1, 11, size=(2, 2))

In [80]:
m12

array([[9, 4],
       [1, 6]])

In [81]:
m13

array([[2, 6],
       [4, 8]])

In [82]:
np.dot(m12, m13)

array([[34, 86],
       [26, 54]])

In [83]:
#14
m14 = np.random.randint(1, 101, size=(5, 5))

In [84]:
m14

array([[23, 11, 72, 33, 88],
       [17, 10,  6, 40, 24],
       [67, 65, 95, 21, 60],
       [79, 99, 64, 72, 51],
       [49, 57, 31, 70, 51]])

In [85]:
np.sum(m14)

1255

In [86]:
#15
m15 = np.random.randint(1, 11, size=(4, 4))
m16 = np.random.randint(1, 11, size=(4, 4))

In [87]:
m15

array([[ 3,  4,  8,  3],
       [ 3,  1,  2, 10],
       [ 2,  6,  5,  6],
       [ 3, 10, 10,  7]])

In [88]:
m16

array([[3, 6, 1, 2],
       [5, 1, 2, 6],
       [4, 8, 6, 9],
       [6, 6, 9, 1]])

In [90]:
m15 - m16


array([[ 0, -2,  7,  1],
       [-2,  0,  0,  4],
       [-2, -2, -1, -3],
       [-3,  4,  1,  6]])

In [91]:
#16
m17 = np.random.random(size=(3, 3))

In [92]:
m17

array([[0.34421508, 0.71489143, 0.90488005],
       [0.35360792, 0.09449936, 0.2101843 ],
       [0.28798578, 0.72046221, 0.0243922 ]])

In [100]:
sum2 = np.sum(m17, axis=1)

In [104]:
sum2

array([1.96398655, 0.65829158, 1.03284018])

In [108]:
sum2.reshape(3, 1)

array([[1.96398655],
       [0.65829158],
       [1.03284018]])

In [109]:
#17
m18 = np.random.randint(1, 11, size=(3, 4))

In [110]:
m18


array([[ 5,  9,  2,  5],
       [ 9,  3,  5,  4],
       [ 3,  9,  2, 10]])

In [111]:
m18 ** 2

array([[ 25,  81,   4,  25],
       [ 81,   9,  25,  16],
       [  9,  81,   4, 100]])

In [112]:
#18
h = np.random.randint(1, 51, size=4)

In [113]:
h

array([14,  5, 20,  3])

In [114]:
h ** 2

array([196,  25, 400,   9])